### PR TITLE
Added scaled dot production attention reordering and upcasting

### LINKED ISSUE #5: Implement Scaled Dot-Product Attention Reordering
Add torch.baddbmm - based reordering in the scaled dot-product attention (see Mistral GPT model). Add flags, set by default to True (this is just a good thing to do) to the GPT configuration.

### LINKED ISSUE #7: Add Upcasting
Add upcasting for the scaled dot-product attention as per Mistral GPT2 implementation. See #5 for more information.

### PR DESCRIPTION
**Pull request by J38**
This branch adds the scaled dot product attention reordering and upcasting (which are tied together) in the _attn method of Attention.

### CODE REVIEW

**Comment by J38** [comment]
It'd be helpful at tomorrow's meeting to talk about how to verify correctness and proper code formatting. I'm not sure what the HF code format is vs. our Mistral format.

**Comment by J38** [comment]
Also this branch won't work at all if not merged with Laurel's work.

**Comment by J38** [comment]
Okay I updated this to set reorder_attn and upscale_attn via the config.

**Comment by siddk** [comment]
Ok - so apparently we didn't pull the latest upstream transformers (my bad - I thought we did) - APIs have changed a bit, so let me reimplement this, using your changes as a guide.

**Pull request closed without merging**
